# Generated by Django 4.1.13 on 2025-08-25 19:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nombredeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='emailusuario',
            field=models.CharField(db_column='EmailUsuario', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sms_code', models.CharField(blank=True, max_length=5, null=True)),
                ('sms_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('email_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email_token_expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nombredeapp.usuarios')),
            ],
        ),
    ]
