# Generated by Django 4.1.13 on 2025-08-26 18:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('nombredeapp', '0002_usuarios_telefono_alter_usuarios_emailusuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSeguridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_ip', models.CharField(max_length=50)),
                ('intento_usuario', models.CharField(max_length=100)),
                ('intento_contrasena', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Registro de Seguridad',
                'verbose_name_plural': 'Registros de Seguridad',
            },
        ),
        migrations.CreateModel(
            name='TokenRecuperacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_sms', models.CharField(blank=True, max_length=5, null=True)),
                ('expiracion_codigo_sms', models.DateTimeField(blank=True, null=True)),
                ('token_email', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expiracion_token_email', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token de Recuperación',
                'verbose_name_plural': 'Tokens de Recuperación',
            },
        ),
        migrations.RemoveField(
            model_name='asistencias',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='cajas',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='cajas',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='caja',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='detallecompras',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='detallecompras',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detalleventas',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detalleventas',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='empleadosxsucursales',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='empleadosxsucursales',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='inventarios',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='inventarios',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='ofertas',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='proveedorxproductos',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='proveedorxproductos',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='proveedorxsucursales',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='proveedorxsucursales',
            name='sucursal',
        ),
        migrations.DeleteModel(
            name='SecurityLog',
        ),
        migrations.RemoveField(
            model_name='sucursales',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='ubicaciones',
            name='codigopostal',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='roles',
        ),
        migrations.AlterUniqueTogether(
            name='usuariosxrol',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usuariosxrol',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='usuariosxrol',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuarioxsucursales',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='usuarioxsucursales',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='caja',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='oferta',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.asistencias',),
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.cajas',),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.categorias',),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.compras',),
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.detallecompras',),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.detalleventas',),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.empleados',),
        ),
        migrations.CreateModel(
            name='EmpleadoPorSucursal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.empleadosxsucursales',),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.inventarios',),
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.ofertas',),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.pedidos',),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.productos',),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.proveedores',),
        ),
        migrations.CreateModel(
            name='ProveedorPorProducto',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.proveedorxproductos',),
        ),
        migrations.CreateModel(
            name='ProveedorPorSucursal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.proveedorxsucursales',),
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.roles',),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.sucursales',),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.ubicaciones',),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.usuarios',),
        ),
        migrations.CreateModel(
            name='UsuarioPorSucursal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.usuarioxsucursales',),
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.usuariosxrol',),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.ventas',),
        ),
        migrations.DeleteModel(
            name='Asistencias',
        ),
        migrations.DeleteModel(
            name='Cajas',
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.DeleteModel(
            name='Codigopostal',
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
        migrations.DeleteModel(
            name='Detallecompras',
        ),
        migrations.DeleteModel(
            name='Detallepedido',
        ),
        migrations.DeleteModel(
            name='Detalleventas',
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
        migrations.DeleteModel(
            name='Empleadosxsucursales',
        ),
        migrations.DeleteModel(
            name='Inventarios',
        ),
        migrations.DeleteModel(
            name='Ofertas',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='Proveedores',
        ),
        migrations.DeleteModel(
            name='Proveedorxproductos',
        ),
        migrations.DeleteModel(
            name='Proveedorxsucursales',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Sucursales',
        ),
        migrations.DeleteModel(
            name='Ubicaciones',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.DeleteModel(
            name='Usuariosxrol',
        ),
        migrations.DeleteModel(
            name='Usuarioxsucursales',
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
        migrations.AddField(
            model_name='tokenrecuperacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nombredeapp.usuario'),
        ),
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.codigopostal',),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('caja.detallepedido',),
        ),
    ]
