# Generated by Django 4.1.13 on 2025-08-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('idasistencia', models.AutoField(db_column='IdAsistencia', primary_key=True, serialize=False)),
                ('fechaasistencia', models.DateField(db_column='FechaAsistencia')),
                ('horaentrada', models.TimeField(db_column='HoraEntrada')),
                ('horasalida', models.TimeField(db_column='HoraSalida')),
            ],
            options={
                'db_table': 'asistencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('idcaja', models.AutoField(db_column='IdCaja', primary_key=True, serialize=False)),
                ('nombrecaja', models.CharField(db_column='NombreCaja', max_length=50)),
                ('horaaperturacaja', models.TimeField(db_column='HoraAperturaCaja')),
                ('horacierrecaja', models.TimeField(db_column='HoraCierreCaja')),
                ('fechaaperturacaja', models.DateField(db_column='FechaAperturaCaja')),
                ('fechacierrecaja', models.DateField(db_column='FechaCierreCaja')),
                ('montoinicialcaja', models.FloatField(db_column='MontoInicialCaja')),
                ('montofinalcaja', models.FloatField(db_column='MontoFinalCaja')),
                ('observacionapertura', models.CharField(blank=True, db_column='Observacionapertura', max_length=100, null=True)),
            ],
            options={
                'db_table': 'cajas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idcategoria', models.AutoField(db_column='IdCategoria', primary_key=True, serialize=False)),
                ('nombrecategoria', models.CharField(db_column='NombreCategoria', max_length=30)),
                ('descripcioncategoria', models.CharField(db_column='DescripcionCategoria', max_length=50)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Codigopostal',
            fields=[
                ('idcodigopostal', models.AutoField(db_column='IdCodigoPostal', primary_key=True, serialize=False)),
                ('codigopostal', models.BigIntegerField(db_column='CodigoPostal')),
                ('nombrelocalidad', models.CharField(db_column='NombreLocalidad', max_length=30)),
            ],
            options={
                'db_table': 'codigopostal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('idcompras', models.AutoField(db_column='IdCompras', primary_key=True, serialize=False)),
                ('fechacompra', models.DateField(db_column='FechaCompra')),
                ('horacompra', models.TimeField(db_column='HoraCompra')),
                ('totalcompra', models.FloatField(db_column='TotalCompra')),
                ('estadocompra', models.CharField(db_column='EstadoCompra', max_length=50)),
            ],
            options={
                'db_table': 'compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallecompras',
            fields=[
                ('iddetallecompras', models.AutoField(db_column='IdDetalleCompras', primary_key=True, serialize=False)),
                ('cantidadcompra', models.IntegerField(db_column='CantidadCompra')),
                ('preciounitariodc', models.FloatField(db_column='PrecioUnitarioDC')),
                ('subtotaldc', models.FloatField(db_column='SubtotalDC')),
            ],
            options={
                'db_table': 'detallecompras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallepedido',
            fields=[
                ('iddetallepedido', models.AutoField(db_column='IdDetallePedido', primary_key=True, serialize=False)),
                ('cantidadpedido', models.IntegerField(db_column='CantidadPedido')),
                ('preciounitariopedido', models.FloatField(db_column='PrecioUnitarioPedido')),
            ],
            options={
                'db_table': 'detallepedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleventas',
            fields=[
                ('iddetalleventas', models.AutoField(db_column='IdDetalleVentas', primary_key=True, serialize=False)),
                ('cantidadvendida', models.IntegerField(db_column='CantidadVendida')),
                ('preciounitariodv', models.FloatField(db_column='PrecioUnitarioDV')),
                ('subtotaldv', models.FloatField(db_column='SubtotalDV')),
            ],
            options={
                'db_table': 'detalleventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('idempleado', models.AutoField(db_column='IdEmpleado', primary_key=True, serialize=False)),
                ('salarioempleado', models.FloatField(db_column='SalarioEmpleado')),
                ('fechacontratado', models.DateField(db_column='FechaContratado')),
                ('cargoempleado', models.CharField(db_column='CargoEmpleado', max_length=100)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleadosxsucursales',
            fields=[
                ('idempleadosucursales', models.AutoField(db_column='IdEmpleadoSucursales', primary_key=True, serialize=False)),
                ('fechaaltaempleado', models.DateField(db_column='FechaAltaEmpleado')),
                ('fechabajaempleado', models.DateField(blank=True, db_column='FechaBajaEmpleado', null=True)),
            ],
            options={
                'db_table': 'empleadosxsucursales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventarios',
            fields=[
                ('idinventario', models.AutoField(db_column='IdInventario', primary_key=True, serialize=False)),
                ('stockactual', models.IntegerField(db_column='StockActual')),
                ('stockminimo', models.IntegerField(db_column='StockMinimo')),
                ('fechareposicion', models.DateField(db_column='FechaReposicion')),
            ],
            options={
                'db_table': 'inventarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('idofertas', models.AutoField(db_column='IdOfertas', primary_key=True, serialize=False)),
                ('nombreoferta', models.CharField(db_column='NombreOferta', max_length=30)),
                ('descripcionoferta', models.CharField(db_column='DescripcionOferta', max_length=50)),
                ('fechainiciooferta', models.DateField(db_column='FechaInicioOferta')),
                ('fechafinoferta', models.DateField(db_column='FechaFinOferta')),
                ('valordescuento', models.FloatField(db_column='ValorDescuento')),
            ],
            options={
                'db_table': 'ofertas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('idpedidos', models.AutoField(db_column='IdPedidos', primary_key=True, serialize=False)),
                ('fechapedido', models.DateField(db_column='FechaPedido')),
                ('fechamaxretiro', models.DateField(db_column='FechaMaxRetiro')),
                ('estadopedido', models.CharField(db_column='EstadoPedido', max_length=30)),
                ('codigoretiro', models.CharField(db_column='CodigoRetiro', max_length=50)),
            ],
            options={
                'db_table': 'pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducto', models.AutoField(db_column='IdProducto', primary_key=True, serialize=False)),
                ('nombreproductos', models.CharField(db_column='NombreProductos', max_length=50)),
                ('precioproducto', models.FloatField(db_column='PrecioProducto')),
                ('marcaproducto', models.CharField(db_column='MarcaProducto', max_length=50)),
                ('codigobarraproducto', models.BigIntegerField(db_column='CodigoBarraProducto')),
                ('imagenproducto', models.TextField(blank=True, db_column='ImagenProducto', null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idproveedor', models.AutoField(db_column='IdProveedor', primary_key=True, serialize=False)),
                ('nombreproveedor', models.CharField(db_column='NombreProveedor', max_length=30)),
                ('telefonoproveedor', models.BigIntegerField(db_column='TelefonoProveedor')),
                ('emailprov', models.CharField(db_column='EmailProv', max_length=30)),
                ('cuitproveedor', models.BigIntegerField(db_column='CUITProveedor')),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedorxproductos',
            fields=[
                ('idproveedorxproducto', models.AutoField(db_column='IdProveedorxProducto', primary_key=True, serialize=False)),
                ('descripcionpxp', models.CharField(db_column='DescripcionPxP', max_length=50)),
            ],
            options={
                'db_table': 'proveedorxproductos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedorxsucursales',
            fields=[
                ('idproveedorsucursal', models.AutoField(db_column='IdProveedorSucursal', primary_key=True, serialize=False)),
                ('fechavisita', models.DateField(db_column='FechaVisita')),
            ],
            options={
                'db_table': 'proveedorxsucursales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idroles', models.AutoField(db_column='IdRoles', primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(db_column='NombreRol', max_length=50)),
                ('descripcionrol', models.CharField(blank=True, db_column='DescripcionRol', max_length=200, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('idsucursal', models.AutoField(db_column='IdSucursal', primary_key=True, serialize=False)),
                ('nombresucursal', models.CharField(db_column='NombreSucursal', max_length=30)),
                ('telefonosucursal', models.BigIntegerField(db_column='TelefonoSucursal')),
            ],
            options={
                'db_table': 'sucursales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('idubicacion', models.AutoField(db_column='IdUbicacion', primary_key=True, serialize=False)),
                ('ciudad', models.CharField(db_column='Ciudad', max_length=50)),
                ('nombrecalle', models.CharField(db_column='NombreCalle', max_length=50)),
                ('barrio', models.CharField(db_column='Barrio', max_length=50)),
            ],
            options={
                'db_table': 'ubicaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuarios', models.AutoField(db_column='IdUsuarios', primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(db_column='NombreUsuario', max_length=30)),
                ('apellidousuario', models.CharField(db_column='ApellidoUsuario', max_length=30)),
                ('emailusuario', models.CharField(db_column='EmailUsuario', max_length=50)),
                ('passwordusuario', models.CharField(db_column='PasswordUsuario', max_length=20)),
                ('fecharegistrousuario', models.DateField(db_column='FechaRegistroUsuario')),
                ('dniusuario', models.BigIntegerField(db_column='DNIUsuario')),
                ('imagenusuario', models.TextField(blank=True, db_column='ImagenUsuario', null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuariosxrol',
            fields=[
                ('idusuariorol', models.AutoField(db_column='IdUsuarioRol', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuariosxrol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarioxsucursales',
            fields=[
                ('idusuariosucursales', models.AutoField(db_column='IdUsuarioSucursales', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuarioxsucursales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('idventa', models.AutoField(db_column='IdVenta', primary_key=True, serialize=False)),
                ('totalventa', models.FloatField(db_column='TotalVenta')),
                ('metodopago', models.CharField(db_column='MetodoPago', max_length=50)),
                ('estadoventa', models.CharField(db_column='EstadoVenta', max_length=50)),
                ('fechaventa', models.DateField(db_column='FechaVenta')),
                ('horaventa', models.TimeField(db_column='HoraVenta')),
            ],
            options={
                'db_table': 'ventas',
                'managed': False,
            },
        ),
    ]
