# Generated by Django 4.1.13 on 2025-08-27 05:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('idarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombrearea', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Área')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('idcaja', models.AutoField(db_column='IdCaja', primary_key=True, serialize=False)),
                ('nombrecaja', models.CharField(db_column='NombreCaja', max_length=50)),
                ('horaaperturacaja', models.TimeField(db_column='HoraAperturaCaja')),
                ('horacierrecaja', models.TimeField(db_column='HoraCierreCaja')),
                ('fechaaperturacaja', models.DateField(db_column='FechaAperturaCaja')),
                ('fechacierrecaja', models.DateField(db_column='FechaCierreCaja')),
                ('montoinicialcaja', models.FloatField(db_column='MontoInicialCaja')),
                ('montofinalcaja', models.FloatField(db_column='MontoFinalCaja')),
                ('observacionapertura', models.CharField(blank=True, db_column='Observacionapertura', max_length=100, null=True)),
            ],
            options={
                'db_table': 'cajas',
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idcategoria', models.AutoField(db_column='IdCategoria', primary_key=True, serialize=False)),
                ('nombrecategoria', models.CharField(db_column='NombreCategoria', max_length=30)),
                ('descripcioncategoria', models.CharField(db_column='DescripcionCategoria', max_length=50)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Codigopostal',
            fields=[
                ('idcodigopostal', models.AutoField(db_column='IdCodigoPostal', primary_key=True, serialize=False)),
                ('codigopostal', models.BigIntegerField(db_column='CodigoPostal')),
                ('nombrelocalidad', models.CharField(db_column='NombreLocalidad', max_length=30)),
            ],
            options={
                'db_table': 'codigopostal',
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('idcompras', models.AutoField(db_column='IdCompras', primary_key=True, serialize=False)),
                ('fechacompra', models.DateField(db_column='FechaCompra')),
                ('horacompra', models.TimeField(db_column='HoraCompra')),
                ('totalcompra', models.FloatField(db_column='TotalCompra')),
                ('estadocompra', models.CharField(db_column='EstadoCompra', max_length=50)),
                ('idcaja', models.ForeignKey(db_column='IdCaja', on_delete=django.db.models.deletion.CASCADE, to='caja.cajas')),
            ],
            options={
                'db_table': 'compras',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('idempleado', models.AutoField(db_column='IdEmpleado', primary_key=True, serialize=False)),
                ('salarioempleado', models.FloatField(db_column='SalarioEmpleado')),
                ('fechacontratado', models.DateField(db_column='FechaContratado')),
                ('cargoempleado', models.CharField(db_column='CargoEmpleado', max_length=100)),
                ('estado', models.CharField(default='Trabajando', max_length=20)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('idofertas', models.AutoField(db_column='IdOfertas', primary_key=True, serialize=False)),
                ('nombreoferta', models.CharField(db_column='NombreOferta', max_length=30)),
                ('descripcionoferta', models.CharField(db_column='DescripcionOferta', max_length=50)),
                ('fechainiciooferta', models.DateField(db_column='FechaInicioOferta')),
                ('fechafinoferta', models.DateField(db_column='FechaFinOferta')),
                ('valordescuento', models.FloatField(db_column='ValorDescuento')),
            ],
            options={
                'db_table': 'ofertas',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducto', models.AutoField(db_column='IdProducto', primary_key=True, serialize=False)),
                ('nombreproductos', models.CharField(db_column='NombreProductos', max_length=50)),
                ('precioproducto', models.FloatField(db_column='PrecioProducto')),
                ('marcaproducto', models.CharField(db_column='MarcaProducto', max_length=50)),
                ('codigobarraproducto', models.BigIntegerField(db_column='CodigoBarraProducto', unique=True)),
                ('imagenproducto', models.TextField(blank=True, db_column='ImagenProducto', null=True)),
                ('idcategoria', models.ForeignKey(db_column='IdCategoria', on_delete=django.db.models.deletion.CASCADE, to='caja.categorias')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idproveedor', models.AutoField(db_column='IdProveedor', primary_key=True, serialize=False)),
                ('nombreproveedor', models.CharField(db_column='NombreProveedor', max_length=30)),
                ('telefonoproveedor', models.BigIntegerField(db_column='TelefonoProveedor')),
                ('emailprov', models.CharField(db_column='EmailProv', max_length=30)),
                ('cuitproveedor', models.BigIntegerField(db_column='CUITProveedor', unique=True)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='RegistroSeguridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_ip', models.CharField(max_length=50)),
                ('intento_usuario', models.CharField(max_length=100)),
                ('intento_contrasena', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idroles', models.AutoField(db_column='IdRoles', primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(db_column='NombreRol', max_length=50)),
                ('descripcionrol', models.CharField(blank=True, db_column='DescripcionRol', max_length=200, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.area')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('idsucursal', models.AutoField(db_column='IdSucursal', primary_key=True, serialize=False)),
                ('nombresucursal', models.CharField(db_column='NombreSucursal', max_length=30)),
                ('telefonosucursal', models.BigIntegerField(db_column='TelefonoSucursal')),
            ],
            options={
                'db_table': 'sucursales',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuarios', models.AutoField(db_column='IdUsuarios', primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(db_column='NombreUsuario', max_length=30, unique=True)),
                ('apellidousuario', models.CharField(db_column='ApellidoUsuario', max_length=30)),
                ('emailusuario', models.CharField(db_column='EmailUsuario', max_length=50, unique=True)),
                ('passwordusuario', models.CharField(db_column='PasswordUsuario', max_length=255)),
                ('fecharegistrousuario', models.DateField(db_column='FechaRegistroUsuario')),
                ('dniusuario', models.BigIntegerField(db_column='DNIUsuario', unique=True)),
                ('imagenusuario', models.TextField(blank=True, db_column='ImagenUsuario', null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('idventa', models.AutoField(db_column='IdVenta', primary_key=True, serialize=False)),
                ('totalventa', models.FloatField(db_column='TotalVenta')),
                ('metodopago', models.CharField(db_column='MetodoPago', max_length=50)),
                ('estadoventa', models.CharField(db_column='EstadoVenta', max_length=50)),
                ('fechaventa', models.DateField(db_column='FechaVenta')),
                ('horaventa', models.TimeField(db_column='HoraVenta')),
                ('idcaja', models.ForeignKey(db_column='IdCaja', on_delete=django.db.models.deletion.CASCADE, to='caja.cajas')),
                ('idofertas', models.ForeignKey(db_column='IdOfertas', on_delete=django.db.models.deletion.CASCADE, to='caja.ofertas')),
                ('idusuarios', models.ForeignKey(db_column='IdUsuarios', on_delete=django.db.models.deletion.CASCADE, to='caja.usuarios')),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='Usuarioxsucursales',
            fields=[
                ('idusuariosucursales', models.AutoField(db_column='IdUsuarioSucursales', primary_key=True, serialize=False)),
                ('idsucursal', models.ForeignKey(db_column='IdSucursal', on_delete=django.db.models.deletion.CASCADE, to='caja.sucursales')),
                ('idusuarios', models.ForeignKey(db_column='IdUsuarios', on_delete=django.db.models.deletion.CASCADE, to='caja.usuarios')),
            ],
            options={
                'db_table': 'usuarioxsucursales',
            },
        ),
        migrations.CreateModel(
            name='Usuariosxrol',
            fields=[
                ('idusuarioxrol', models.AutoField(primary_key=True, serialize=False)),
                ('idroles', models.ForeignKey(db_column='IdRoles', on_delete=django.db.models.deletion.CASCADE, to='caja.roles')),
                ('idusuarios', models.ForeignKey(db_column='IdUsuarios', on_delete=django.db.models.deletion.CASCADE, to='caja.usuarios')),
            ],
            options={
                'db_table': 'usuariosxrol',
                'unique_together': {('idusuarios', 'idroles')},
            },
        ),
        migrations.AddField(
            model_name='usuarios',
            name='roles',
            field=models.ManyToManyField(through='caja.Usuariosxrol', to='caja.roles'),
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('idubicacion', models.AutoField(db_column='IdUbicacion', primary_key=True, serialize=False)),
                ('ciudad', models.CharField(db_column='Ciudad', max_length=50)),
                ('nombrecalle', models.CharField(db_column='NombreCalle', max_length=50)),
                ('barrio', models.CharField(db_column='Barrio', max_length=50)),
                ('idcodigopostal', models.ForeignKey(db_column='IdCodigoPostal', on_delete=django.db.models.deletion.CASCADE, to='caja.codigopostal')),
            ],
            options={
                'db_table': 'ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='TokenRecuperacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_sms', models.CharField(blank=True, max_length=5, null=True)),
                ('expiracion_codigo_sms', models.DateTimeField(blank=True, null=True)),
                ('token_email', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expiracion_token_email', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='sucursales',
            name='idubicacion',
            field=models.ForeignKey(db_column='IdUbicacion', on_delete=django.db.models.deletion.CASCADE, to='caja.ubicaciones'),
        ),
        migrations.CreateModel(
            name='Proveedorxsucursales',
            fields=[
                ('idproveedorsucursal', models.AutoField(db_column='IdProveedorSucursal', primary_key=True, serialize=False)),
                ('fechavisita', models.DateField(db_column='FechaVisita')),
                ('idproveedor', models.ForeignKey(db_column='IdProveedor', on_delete=django.db.models.deletion.CASCADE, to='caja.proveedores')),
                ('idsucursal', models.ForeignKey(db_column='IdSucursal', on_delete=django.db.models.deletion.CASCADE, to='caja.sucursales')),
            ],
            options={
                'db_table': 'proveedorxsucursales',
            },
        ),
        migrations.CreateModel(
            name='Proveedorxproductos',
            fields=[
                ('idproveedorxproducto', models.AutoField(db_column='IdProveedorxProducto', primary_key=True, serialize=False)),
                ('descripcionpxp', models.CharField(db_column='DescripcionPxP', max_length=50)),
                ('idproducto', models.ForeignKey(db_column='IdProducto', on_delete=django.db.models.deletion.CASCADE, to='caja.productos')),
                ('idproveedor', models.ForeignKey(db_column='IdProveedor', on_delete=django.db.models.deletion.CASCADE, to='caja.proveedores')),
            ],
            options={
                'db_table': 'proveedorxproductos',
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('idpedidos', models.AutoField(db_column='IdPedidos', primary_key=True, serialize=False)),
                ('fechapedido', models.DateField(db_column='FechaPedido')),
                ('fechamaxretiro', models.DateField(db_column='FechaMaxRetiro')),
                ('estadopedido', models.CharField(db_column='EstadoPedido', max_length=30)),
                ('codigoretiro', models.CharField(db_column='CodigoRetiro', max_length=50)),
                ('idsucursal', models.ForeignKey(db_column='IdSucursal', on_delete=django.db.models.deletion.CASCADE, to='caja.sucursales')),
                ('idusuarios', models.ForeignKey(db_column='IdUsuarios', on_delete=django.db.models.deletion.CASCADE, to='caja.usuarios')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.AddField(
            model_name='ofertas',
            name='idproducto',
            field=models.ForeignKey(db_column='IdProducto', on_delete=django.db.models.deletion.CASCADE, to='caja.productos'),
        ),
        migrations.CreateModel(
            name='Empleadosxsucursales',
            fields=[
                ('idempleadosucursales', models.AutoField(db_column='IdEmpleadoSucursales', primary_key=True, serialize=False)),
                ('fechaaltaempleado', models.DateField(db_column='FechaAltaEmpleado')),
                ('fechabajaempleado', models.DateField(blank=True, db_column='FechaBajaEmpleado', null=True)),
                ('idempleado', models.ForeignKey(db_column='IdEmpleado', on_delete=django.db.models.deletion.CASCADE, to='caja.empleados')),
                ('idsucursal', models.ForeignKey(db_column='IdSucursal', on_delete=django.db.models.deletion.CASCADE, to='caja.sucursales')),
            ],
            options={
                'db_table': 'empleadosxsucursales',
            },
        ),
        migrations.AddField(
            model_name='empleados',
            name='idusuarios',
            field=models.OneToOneField(db_column='IdUsuarios', on_delete=django.db.models.deletion.CASCADE, to='caja.usuarios'),
        ),
        migrations.CreateModel(
            name='Detalleventas',
            fields=[
                ('iddetalleventas', models.AutoField(db_column='IdDetalleVentas', primary_key=True, serialize=False)),
                ('cantidadvendida', models.IntegerField(db_column='CantidadVendida')),
                ('preciounitariodv', models.FloatField(db_column='PrecioUnitarioDV')),
                ('subtotaldv', models.FloatField(db_column='SubtotalDV')),
                ('idprducto', models.ForeignKey(db_column='IdPrducto', on_delete=django.db.models.deletion.CASCADE, to='caja.productos')),
                ('idventa', models.ForeignKey(db_column='IdVenta', on_delete=django.db.models.deletion.CASCADE, to='caja.ventas')),
            ],
            options={
                'db_table': 'detalleventas',
            },
        ),
        migrations.CreateModel(
            name='Detallepedido',
            fields=[
                ('iddetallepedido', models.AutoField(db_column='IdDetallePedido', primary_key=True, serialize=False)),
                ('cantidadpedido', models.IntegerField(db_column='CantidadPedido')),
                ('preciounitariopedido', models.FloatField(db_column='PrecioUnitarioPedido')),
                ('idpedidos', models.ForeignKey(db_column='IdPedidos', on_delete=django.db.models.deletion.CASCADE, to='caja.pedidos')),
                ('idproducto', models.ForeignKey(db_column='IdProducto', on_delete=django.db.models.deletion.CASCADE, to='caja.productos')),
            ],
            options={
                'db_table': 'detallepedido',
            },
        ),
        migrations.CreateModel(
            name='Detallecompras',
            fields=[
                ('iddetallecompras', models.AutoField(db_column='IdDetalleCompras', primary_key=True, serialize=False)),
                ('cantidadcompra', models.IntegerField(db_column='CantidadCompra')),
                ('preciounitariodc', models.FloatField(db_column='PrecioUnitarioDC')),
                ('subtotaldc', models.FloatField(db_column='SubtotalDC')),
                ('idcompras', models.ForeignKey(db_column='IdCompras', on_delete=django.db.models.deletion.CASCADE, to='caja.compras')),
                ('idproducto', models.ForeignKey(db_column='IdProducto', on_delete=django.db.models.deletion.CASCADE, to='caja.productos')),
            ],
            options={
                'db_table': 'detallecompras',
            },
        ),
        migrations.AddField(
            model_name='compras',
            name='idproveedor',
            field=models.ForeignKey(db_column='IdProveedor', on_delete=django.db.models.deletion.CASCADE, to='caja.proveedores'),
        ),
        migrations.AddField(
            model_name='cajas',
            name='idsucursal',
            field=models.ForeignKey(db_column='IdSucursal', on_delete=django.db.models.deletion.CASCADE, to='caja.sucursales'),
        ),
        migrations.AddField(
            model_name='cajas',
            name='idusuarios',
            field=models.ForeignKey(db_column='IdUsuarios', on_delete=django.db.models.deletion.CASCADE, to='caja.usuarios'),
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('idasistencia', models.AutoField(db_column='IdAsistencia', primary_key=True, serialize=False)),
                ('fechaasistencia', models.DateField(db_column='FechaAsistencia')),
                ('horaentrada', models.TimeField(db_column='HoraEntrada')),
                ('horasalida', models.TimeField(db_column='HoraSalida')),
                ('idempleado', models.ForeignKey(db_column='IdEmpleado', on_delete=django.db.models.deletion.CASCADE, to='caja.empleados')),
            ],
            options={
                'db_table': 'asistencias',
            },
        ),
    ]
