# Generated by Django 4.1.13 on 2025-09-01 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('idherramienta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Herramienta')),
                ('url_nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de URL (para {% url %})')),
                ('icono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clase del Icono (ej: fa-users)')),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
                'db_table': 'herramientas',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('idpermiso', models.AutoField(primary_key=True, serialize=False)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.herramienta')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='caja.roles')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permisos',
                'unique_together': {('rol', 'herramienta')},
            },
        ),
    ]
