# Generated by Django 4.1.13 on 2025-09-06 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_herramienta_permiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencias',
            name='rol',
            field=models.ForeignKey(blank=True, help_text='Rol con el que se registró esta asistencia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.roles'),
        ),
        migrations.AlterField(
            model_name='asistencias',
            name='horasalida',
            field=models.TimeField(blank=True, db_column='HoraSalida', null=True),
        ),
    ]
