# Generated by Django 4.1.13 on 2025-09-18 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_asistencias_rol_alter_asistencias_horasalida'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDeVentas',
            fields=[
                ('iddetalleventas', models.AutoField(db_column='IdDetalleVentas', primary_key=True, serialize=False)),
                ('cantidadvendida', models.IntegerField(db_column='CantidadVendida')),
                ('preciounitariodv', models.FloatField(db_column='PrecioUnitarioDV')),
                ('subtotaldv', models.FloatField(db_column='SubtotalDV')),
                ('idproducto', models.ForeignKey(db_column='IdProducto', on_delete=django.db.models.deletion.CASCADE, to='caja.productos')),
                ('idventa', models.ForeignKey(db_column='IdVenta', on_delete=django.db.models.deletion.CASCADE, to='caja.ventas')),
            ],
            options={
                'db_table': 'detalleDeVentas',
            },
        ),
        migrations.CreateModel(
            name='EmpxSuc',
            fields=[
                ('idempxsuc', models.AutoField(primary_key=True, serialize=False)),
                ('idempleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.empleados')),
                ('idsucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.sucursales')),
            ],
            options={
                'db_table': 'empxSuc',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idhorario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField()),
                ('semana_del_mes', models.IntegerField(default=1)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='caja.empleados')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='caja.roles')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horarios',
            },
        ),
        migrations.CreateModel(
            name='Inventarios',
            fields=[
                ('idinventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.productos')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.sucursales')),
            ],
            options={
                'db_table': 'inventarios',
                'unique_together': {('producto', 'sucursal')},
            },
        ),
        migrations.CreateModel(
            name='Provxprod',
            fields=[
                ('idprovxprod', models.AutoField(primary_key=True, serialize=False)),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.productos')),
                ('idproveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.proveedores')),
            ],
            options={
                'db_table': 'provxprod',
            },
        ),
        migrations.CreateModel(
            name='Provxsuc',
            fields=[
                ('idprovxsuc', models.AutoField(primary_key=True, serialize=False)),
                ('idproveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.proveedores')),
                ('idsucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.sucursales')),
            ],
            options={
                'db_table': 'provxsuc',
            },
        ),
        migrations.CreateModel(
            name='UsuxSuc',
            fields=[
                ('idusuxsuc', models.AutoField(primary_key=True, serialize=False)),
                ('idsucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.sucursales')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.usuarios')),
            ],
            options={
                'db_table': 'usuxSuc',
            },
        ),
        migrations.RenameModel(
            old_name='Cajas',
            new_name='Caja',
        ),
        migrations.RenameModel(
            old_name='Detallecompras',
            new_name='DetalleDeCompras',
        ),
        migrations.RenameModel(
            old_name='Detallepedido',
            new_name='DetalleDePedidos',
        ),
        migrations.RenameModel(
            old_name='Usuariosxrol',
            new_name='UsuxRoles',
        ),
        migrations.RemoveField(
            model_name='detalleventas',
            name='idprducto',
        ),
        migrations.RemoveField(
            model_name='detalleventas',
            name='idventa',
        ),
        migrations.RemoveField(
            model_name='empleadosxsucursales',
            name='idempleado',
        ),
        migrations.RemoveField(
            model_name='empleadosxsucursales',
            name='idsucursal',
        ),
        migrations.AlterUniqueTogether(
            name='permiso',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='permiso',
            name='herramienta',
        ),
        migrations.RemoveField(
            model_name='permiso',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='proveedorxproductos',
            name='idproducto',
        ),
        migrations.RemoveField(
            model_name='proveedorxproductos',
            name='idproveedor',
        ),
        migrations.RemoveField(
            model_name='proveedorxsucursales',
            name='idproveedor',
        ),
        migrations.RemoveField(
            model_name='proveedorxsucursales',
            name='idsucursal',
        ),
        migrations.DeleteModel(
            name='RegistroSeguridad',
        ),
        migrations.RemoveField(
            model_name='tokenrecuperacion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuarioxsucursales',
            name='idsucursal',
        ),
        migrations.RemoveField(
            model_name='usuarioxsucursales',
            name='idusuarios',
        ),
        migrations.AlterModelTable(
            name='caja',
            table='caja',
        ),
        migrations.AlterModelTable(
            name='codigopostal',
            table='codigosPostales',
        ),
        migrations.AlterModelTable(
            name='detalledecompras',
            table='detalleDeCompras',
        ),
        migrations.AlterModelTable(
            name='detalledepedidos',
            table='detalleDePedidos',
        ),
        migrations.AlterModelTable(
            name='usuxroles',
            table='usuxRoles',
        ),
        migrations.DeleteModel(
            name='Detalleventas',
        ),
        migrations.DeleteModel(
            name='Empleadosxsucursales',
        ),
        migrations.DeleteModel(
            name='Herramienta',
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
        migrations.DeleteModel(
            name='Proveedorxproductos',
        ),
        migrations.DeleteModel(
            name='Proveedorxsucursales',
        ),
        migrations.DeleteModel(
            name='TokenRecuperacion',
        ),
        migrations.DeleteModel(
            name='Usuarioxsucursales',
        ),
    ]
