# Generated by Django 4.1.13 on 2025-09-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_detalledeventas_empxsuc_horario_inventarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='area',
        ),
        migrations.AddField(
            model_name='roles',
            name='nombrearea',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
