# Generated by Django 4.1.13 on 2025-10-22 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_remove_roles_area_roles_nombrearea_delete_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientosdecaja',
            fields=[
                ('idmovcaja', models.AutoField(db_column='IdMovCaja', primary_key=True, serialize=False)),
                ('nombreusuariomovcaja', models.CharField(db_column='NombreUsuarioMovCaja', max_length=50)),
                ('fechamovcaja', models.DateField(db_column='FechaMovCaja')),
                ('horamovcaja', models.TimeField(db_column='HoraMovCaja')),
                ('nombrecajamovcaja', models.CharField(db_column='NombreCajaMovCaja', max_length=50)),
                ('tipomovcaja', models.CharField(db_column='TipoMovCaja', max_length=50)),
                ('conceptomovcaja', models.CharField(db_column='ConceptoMovCaja', max_length=50)),
                ('valormovcaja', models.FloatField(db_column='ValorMovCaja')),
                ('saldomovcaja', models.FloatField(db_column='SaldoMovCaja')),
                ('idcaja', models.ForeignKey(blank=True, db_column='IdCaja', null=True, on_delete=django.db.models.deletion.CASCADE, to='caja.caja')),
                ('idusuarios', models.ForeignKey(blank=True, db_column='IdUsuarios', null=True, on_delete=django.db.models.deletion.CASCADE, to='caja.usuarios')),
            ],
            options={
                'db_table': 'movimientosdecaja',
            },
        ),
    ]
