# Generated by Django 4.1.13 on 2025-10-22 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_movimientosdecaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='idsucursal',
            field=models.ForeignKey(blank=True, db_column='IdSucursal', null=True, on_delete=django.db.models.deletion.CASCADE, to='caja.sucursales'),
        ),
    ]
