# Generated by Django 4.1.13 on 2025-10-22 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0007_alter_caja_idsucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='idsucursal',
            field=models.ForeignKey(db_column='IdSucursal', on_delete=django.db.models.deletion.CASCADE, to='caja.sucursales'),
        ),
    ]
