# Generated by Django 4.2.16 on 2025-11-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0008_alter_caja_idsucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='saldo_actual',
            field=models.FloatField(db_column='SaldoActual', default=0.0),
        ),
    ]
