# Generated by Django 4.2.16 on 2025-11-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0009_caja_saldo_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='efectivo_actual',
            field=models.FloatField(db_column='EfectivoActual', default=0.0),
        ),
    ]
