# Generated by Django 4.2.16 on 2025-11-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0010_caja_efectivo_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='observacioncierre',
            field=models.CharField(blank=True, db_column='Observacioncierre', max_length=100, null=True),
        ),
    ]
