# Generated by Django 4.2.16 on 2025-11-26 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0011_caja_observacioncierre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('idperiodo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cerrado', models.BooleanField(default=False)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'periodos_nomina',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PagoNomina',
            fields=[
                ('idpago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Cheque', 'Cheque')], max_length=50)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('comprobante', models.CharField(blank=True, max_length=100)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.empleados')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.usuarios')),
            ],
            options={
                'db_table': 'pagos_nomina',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='DeudaNomina',
            fields=[
                ('iddeuda', models.AutoField(primary_key=True, serialize=False)),
                ('total_adeudado', models.FloatField(default=0.0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deuda_nomina', to='caja.empleados')),
            ],
            options={
                'db_table': 'deuda_nomina',
            },
        ),
        migrations.CreateModel(
            name='RegistroNominaSemanal',
            fields=[
                ('idregistro', models.AutoField(primary_key=True, serialize=False)),
                ('horas_trabajadas', models.FloatField(default=0.0)),
                ('monto_devengado', models.FloatField(default=0.0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.empleados')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.periodonomina')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.roles')),
            ],
            options={
                'db_table': 'registro_nomina_semanal',
                'unique_together': {('empleado', 'periodo', 'rol')},
            },
        ),
    ]
