# Generated by Django 4.2.16 on 2025-11-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0012_periodonomina_pagonomina_deudanomina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='fechavencimiento',
            field=models.DateField(blank=True, db_column='FechaVencimiento', null=True),
        ),
    ]
