# Generated by Django 4.2.16 on 2025-11-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0012_periodonomina_pagonomina_deudanomina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='codigo_telefonico',
            field=models.CharField(default='+54', max_length=10),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
