# Generated by Django 4.1.13 on 2025-09-06 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0002_herramienta_permiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaHorario',
            fields=[
                ('iddiahorario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField()),
                ('semana_del_mes', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Día de Horario',
                'verbose_name_plural': 'Días de Horario',
                'db_table': 'dias_horario',
            },
        ),
        migrations.CreateModel(
            name='TramoHorario',
            fields=[
                ('idtramohorario', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dia_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='asistencias.diahorario')),
            ],
            options={
                'verbose_name': 'Tramo Horario',
                'verbose_name_plural': 'Tramos Horarios',
                'db_table': 'tramos_horario',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idhorario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_horario', models.CharField(default='Horario Principal', max_length=100)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='caja.empleados')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horarios',
            },
        ),
        migrations.AddField(
            model_name='diahorario',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='asistencias.horario'),
        ),
    ]
