# Generated by Django 4.1.13 on 2025-09-06 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_asistencias_rol_alter_asistencias_horasalida'),
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='caja.roles'),
        ),
    ]
