# Generated by Django 4.1.13 on 2025-09-07 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0002_horario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diahorario',
            name='semana_del_mes',
        ),
    ]
