# Generated by Django 4.1.13 on 2025-09-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0003_remove_diahorario_semana_del_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='diahorario',
            name='semana_del_mes',
            field=models.IntegerField(default=1),
        ),
    ]
