# Generated by Django 4.1.13 on 2025-09-18 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0004_diahorario_semana_del_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='tramohorario',
            name='dia_horario',
        ),
        migrations.DeleteModel(
            name='DiaHorario',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='TramoHorario',
        ),
    ]
